  name: conditional-step

  on:
    workflow_call:
      inputs:
        SHOULD_RUN:
          description: Should it run?
          type: boolean
          required: false
          default: false

  jobs:
    job-with-conditional-step:
      runs-on: ubuntu-20.04
      steps:
        - name: "First step ${{inputs.SHOULD_RUN}} :D"
          id: first-step
          run: >
            echo "This is the first step"

        - name: "Conditional step"
          if: ${{github.event.inputs.SHOULD_RUN}} == 'true' && steps.first-step.conclusion == 'success'
          run: echo "This is the conditional step"

        - name: "Last step"
          run: echo "This is the last step"
