  name: master-artifact

  on:
    push:
      branches:
        - master

  jobs:
    generate-artifact:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v2
        - name: Create tag
          uses: "./.github/workflows/coverage-add-tag.yaml"
          with:
            commit_sha: ${{ github.event.push.head_commit }}
            coverage: "0.8"
