  name: pr-artifact

  on: [pull_request]

  permissions: write-all

  jobs:
    generate-artifact:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: ${{ github.event.pull_request.head.sha }}
        - name: Analyze tags
          id: analyze-tags
          run: |
            current_coverage="${{ github.event.pull_request.title }}"
            last_coverage_tag=$(git describe --tags --abbrev=0 --first-parent --match="xcoverage-*" || echo "notfound")
            echo "Last coverage tag = $last_coverage_tag"
            coverage="${last_coverage_tag##*-}"
            echo "Last coverage = $coverage"
            
            if [ "$my_variable" == "notfound" ]; then
              label_to_add=""
            else
              lowers_coverage=$(echo "$coverage > $current_coverage" |bc -l)
              echo "lowers_coverage = $lowers_coverage"
            fi
            
            if [ "$lowers_coverage" -gt "0" ]; then
              label_to_add="good-coverage"
            else
              label_to_add="low-covers"
            fi          

        - name: Add label to PR
          if: ${{ steps.analyze-tags.outputs.label_to_add != '' }}
          uses: actions/github-script@v7
          with:
            script: |
              github.rest.issues.removeLabel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['good-coverage', 'low-covers']
              })
              
              github.rest.issues.addLabels({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                labels: ['${{ steps.analyze-tags.outputs.label_to_add }}']
              })
