  name: pr-artifact

  on: [pull_request]

  jobs:
    generate-artifact:
      runs-on: ubuntu-20.04
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            ref: ${{ github.event.pull_request.head.sha }}
        - name: Analyze tags
          run: |
            last_coverage_tag=$(git describe --tags --abbrev=0 --match="coverage-*")
            echo "Last coverage tag = $last_coverage_tag"
            coverage="${last_coverage_tag##*-}"
            echo "Last coverage = $coverage"
