name: get-pr-number

on:
  workflow_run: ["pr-artifact"]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: "Define constants"
        id: constants
        run: |
          pr_number=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                "https://api.github.com/repos/${{ github.repository }}/commits/${{ github.event.workflow_run.head_commit.id }}/pulls" \
                | jq -r '.[0].number')
          echo "pr_number=$pr_number" >>> $GITHUB_OUTPUT