name: get-pr-number

on:
  workflow_run:
    workflows: [ "pr-artifact" ]
    types:
      - completed

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: "Define constants"
        id: constants
        run: |
          pr_number="${{ github.event.workflow_run.pull_requests[0].number }}"
          echo "json = ${{ toJSON(github.event.workflow_run.pull_requests) }}""
          echo "pr_number=$pr_number" >> $GITHUB_OUTPUT
          echo "pr_number=$pr_number"
