  name: set-check-status

  on:
    workflow_dispatch:
      inputs:
        CHECK_NAME:
          description: Check's name
          type: string
          required: true
        CHECK_STATUS:
          description: Check's status
          type: string
          required: true
        COMMIT_SHA:
          description: Commit SHA
          type: string
          required: true


  permissions: read-all

  jobs:
    show-artifact:
      runs-on: ubuntu-20.04
      steps:
        - name: Set check status to success
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/statuses/${{ inputs.COMMIT_SHA }} \
              -d '{
                    "state": "${{ inputs.CHECK_STATUS }}",
                    "description": "line coverage OK",
                    "context": "${{ inputs.CHECK_NAME }}"
                 }'