  name: show-artifact

  on:
    workflow_run:
      workflows:
        - pr-artifact
      types:
        - completed

  jobs:
    show-artifact:
      runs-on: ubuntu-20.04
      steps:
        - name: "Debug trigger event"
          run:
            cat "github.event.workflow_run=${{ toJSON(github.event.workflow_run) }}"
        - name: "Download artifact"
          uses: actions/download-artifact@v4
          with:
            name: pr_name
            path: pr_name.txt
        - name: "Verify pr_name.txt content"
          run: |
            cat pr_name.txt