  name: show-artifact

  on:
    workflow_run:
      workflows:
        - pr-artifact
      types:
        - completed

  jobs:
    show-artifact:
      runs-on: ubuntu-20.04
      steps:
        - name: "Download artifact from run ${{ github.event.workflow_run.id }}"
          uses: actions/download-artifact@v4
          with:
            name: pr_name
            path: pr_name
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ github.token }}
        - name: "Verify pr_name.txt content"
          run: |
            cat pr_name/pr_name.txt