  name: show-artifact-as-check

  on: [pull_request]

  permissions: read-all

  jobs:
    show-artifact:
      runs-on: ubuntu-20.04
      steps:
        - name: Wait for tests to succeed
          uses: lewagon/wait-on-check-action@v1.3.4
          with:
            ref: ${{ github.ref }}
            check-name: 'generate-artifact'
            repo-token: ${{ secrets.GITHUB_TOKEN }}
            wait-interval: 10
        - name: "Download artifact from run ${{ github.event.workflow_run.id }}"
          uses: actions/download-artifact@v4
          with:
            name: pr_name
            path: pr_name
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ github.token }}
        - name: "Verify pr_name.txt content"
          run: |
            cat pr_name/pr_name.txt