  name: show-artifact

  on:
    workflow_run:
      workflows:
        - pr-artifact
      types:
        - completed

  permissions: write-all

  jobs:
    show-artifact:
      runs-on: ubuntu-20.04
      steps:
        - name: "Download artifact from run ${{ github.event.workflow_run.id }}"
          uses: actions/download-artifact@v4
          with:
            name: pr_name
            path: pr_name
            run-id: ${{ github.event.workflow_run.id }}
            github-token: ${{ github.token }}
        - name: "Verify pr_name.txt content"
          run: |
            cat pr_name/pr_name.txt
        - name: Update PR status
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: |
            curl -X POST \
              -H "Accept: application/vnd.github.v3+json" \
              -H "Authorization: token $GITHUB_TOKEN" \
              https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.event.workflow_run.head_commit.id }} \
              -d '{
                    "state": "success",
                    "description": "Workflow show-artifact completed",
                    "context": "continuous-integration/show-artifact"
                 }'